# Generated by Django 5.0.6 on 2025-06-17 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0002_alter_cafecontact_cafe_alter_cafecontact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_order_id',
            field=models.CharField(blank=True, help_text='Уникальный ID заказа на стороне клиента', max_length=100, null=True),
        ),
    ]
