# Generated by Django 5.0.6 on 2025-06-17 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0004_order_customer_name_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('in_place', 'В ресторане'), ('delivery', 'Доставка'), ('pickup', 'Самовывоз')], max_length=20),
        ),
    ]
